stages:
  - install
  - format
  - build

variables:
  NPM_CONFIG_LOGLEVEL: warn
  NPM_CONFIG_CACHE: '$CI_PROJECT_DIR/.npm'

install:
  stage: install
  image: node:18
  script:
    - rm -rf node_modules .npm
    - npm ci
  cache:
    key: '${CI_COMMIT_REF_SLUG}'
    paths:
      - .npm
      - node_modules/
    policy: pull-push
  artifacts:
    paths:
      - node_modules/
    expire_in: 1h
  rules:
    - if: $CI_MERGE_REQUEST_ID

deadcode:
  stage: format
  image: node:18
  needs:
    - job: install
      artifacts: true
  script:
    - npm run deadcode
  cache:
    key: '${CI_COMMIT_REF_SLUG}'
    paths:
      - .npm
      - node_modules/
    policy: pull
  rules:
    - if: $CI_MERGE_REQUEST_ID

lint:
  stage: format
  image: node:18
  needs:
    - job: install
      artifacts: true
  script:
    - npm run lint
  cache:
    key: '${CI_COMMIT_REF_SLUG}'
    paths:
      - .npm
      - node_modules/
    policy: pull
  rules:
    - if: $CI_MERGE_REQUEST_ID

build:
  stage: build
  image: node:18
  needs:
    - job: install
      artifacts: true
  script:
    - rm -rf .next
    - npm run build
  cache:
    key: '${CI_COMMIT_REF_SLUG}'
    paths:
      - .npm
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - .next/
    expire_in: 1h
  rules:
    - if: $CI_MERGE_REQUEST_ID
